name: Tagged Alpha release

permissions:
  contents: "write"
  packages: "write"
  pull-requests: "read"

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-alpha[0-9]{2,}"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean assembleAlpha -Pgithub

      - uses: r0adkll/sign-android-release@v1
        id: sign_base_app
        with:
          releaseDirectory: app/build/outputs/apk/base/alpha
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - uses: r0adkll/sign-android-release@v1
        id: sign_plus_app
        with:
          releaseDirectory: app/build/outputs/apk/plus/alpha
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Install mmv
        run: |
          sudo apt-get update
          sudo apt-get install mmv

      - name: Delete unsigned apks
        run: |
          cd ${GITHUB_WORKSPACE}/app/build/outputs/apk/base/alpha
          rm *-unsigned-aligned.apk
          cd ${GITHUB_WORKSPACE}/app/build/outputs/apk/plus/alpha
          rm *-unsigned-aligned.apk

      - name: Rename signed apks
        run: |
          cd ${GITHUB_WORKSPACE}/app/build/outputs/apk/base/alpha
          mmv '*-alpha-unsigned-signed.apk' '#1-${{ github.ref_name }}.apk'
          cd ${GITHUB_WORKSPACE}/app/build/outputs/apk/plus/alpha
          mmv '*-alpha-unsigned-signed.apk' '#1-${{ github.ref_name }}.apk'

      - uses: actions/upload-artifact@v3
        with:
          name: signed_apks_${{ github.ref_name }}
          path: app/build/outputs/apk/*/alpha/*-${{ github.ref_name }}.apk

      - name: Create Draft Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ github.ref_name }}"
          prerelease: true
          draft: true
          files: app/build/outputs/apk/*/alpha/*-${{ github.ref_name }}.apk
